// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teknosib.DataAccess.EntitiyFramework;

#nullable disable

namespace Teknosib.DataAccess.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teknosib.Entity.Models.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AddressId");

                    b.ToTable("Tbl_Address", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.AppUser", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AppUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LegalEntityId");

                    b.ToTable("Tbl_AppUser", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.ToTable("Tbl_Category", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompletedProjects")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Tbl_LegalEntity", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("OwnerLegalEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("P_Status")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProblemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerLegalEntityId");

                    b.ToTable("Tbl_Problem", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ComplatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("FunderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.HasIndex("FunderId");

                    b.HasIndex("ProblemId")
                        .IsUnique();

                    b.HasIndex("ProviderId");

                    b.ToTable("Tbl_Project", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Proposal", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppliedSupportCallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfferDetails")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProposalStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderLegalEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProposalId");

                    b.HasIndex("AppliedSupportCallId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("ProviderLegalEntityId");

                    b.ToTable("Tbl_Proposal", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Tbl_Review", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.SupportCall", b =>
                {
                    b.Property<Guid>("SupportCallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<Guid>("PublisherLegalEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("SupportAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SupportCallId");

                    b.HasIndex("PublisherLegalEntityId");

                    b.ToTable("Tbl_SupportCall", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Company", b =>
                {
                    b.HasBaseType("Teknosib.Entity.Models.LegalEntity");

                    b.Property<string>("ContentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("EmployeeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ExperienceYear")
                        .HasColumnType("int");

                    b.Property<string>("ExpertiseAreas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.ToTable("Tbl_Company", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Institution", b =>
                {
                    b.HasBaseType("Teknosib.Entity.Models.LegalEntity");

                    b.Property<string>("AuthorityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AuthorityTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OfficialTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ToTable("Tbl_Institution", (string)null);
                });

            modelBuilder.Entity("Teknosib.Entity.Models.AppUser", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.LegalEntity", "LegalEntity")
                        .WithMany("AppUsers")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.LegalEntity", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("Teknosib.Entity.Models.LegalEntity", "AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Problem", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.Category", "Category")
                        .WithMany("Problem")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teknosib.Entity.Models.LegalEntity", "OwnerLegalEntity")
                        .WithMany("OwnedProblems")
                        .HasForeignKey("OwnerLegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("OwnerLegalEntity");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Project", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.LegalEntity", "Client")
                        .WithMany("ClientProjects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teknosib.Entity.Models.LegalEntity", "Funder")
                        .WithMany("FunderProjects")
                        .HasForeignKey("FunderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Teknosib.Entity.Models.Problem", "Problem")
                        .WithOne("Project")
                        .HasForeignKey("Teknosib.Entity.Models.Project", "ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teknosib.Entity.Models.LegalEntity", "Provider")
                        .WithMany("ProviderProjects")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Funder");

                    b.Navigation("Problem");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Proposal", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.SupportCall", "AppliedSupportCall")
                        .WithMany()
                        .HasForeignKey("AppliedSupportCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Teknosib.Entity.Models.Problem", "Problem")
                        .WithMany("Proposal")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teknosib.Entity.Models.LegalEntity", "ProviderLegalEntity")
                        .WithMany("SubmittedProposals")
                        .HasForeignKey("ProviderLegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppliedSupportCall");

                    b.Navigation("Problem");

                    b.Navigation("ProviderLegalEntity");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Review", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.Project", "Project")
                        .WithOne()
                        .HasForeignKey("Teknosib.Entity.Models.Review", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teknosib.Entity.Models.AppUser", "Reviewee")
                        .WithMany("ReviewsRecevid")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teknosib.Entity.Models.AppUser", "Reviewer")
                        .WithMany("ReviewWritten")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.SupportCall", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.LegalEntity", "PublisherLegalEntity")
                        .WithMany("PublishedSupportCalls")
                        .HasForeignKey("PublisherLegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PublisherLegalEntity");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Company", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.LegalEntity", null)
                        .WithOne()
                        .HasForeignKey("Teknosib.Entity.Models.Company", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Institution", b =>
                {
                    b.HasOne("Teknosib.Entity.Models.LegalEntity", null)
                        .WithOne()
                        .HasForeignKey("Teknosib.Entity.Models.Institution", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Teknosib.Entity.Models.AppUser", b =>
                {
                    b.Navigation("ReviewWritten");

                    b.Navigation("ReviewsRecevid");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Category", b =>
                {
                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.LegalEntity", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("ClientProjects");

                    b.Navigation("FunderProjects");

                    b.Navigation("OwnedProblems");

                    b.Navigation("ProviderProjects");

                    b.Navigation("PublishedSupportCalls");

                    b.Navigation("SubmittedProposals");
                });

            modelBuilder.Entity("Teknosib.Entity.Models.Problem", b =>
                {
                    b.Navigation("Project")
                        .IsRequired();

                    b.Navigation("Proposal");
                });
#pragma warning restore 612, 618
        }
    }
}
